"""
Regression guards for the ship-time PR body losing its commit text.

BACKGROUND: `gates ship` once opened PRs with the host CLI's own
commit-message fill, so the PR body carried every commit subject and body.
A later change switched to a rendered body file, and the rendered "What
changed and why" section became a placeholder -- the commit text was
discarded. Nothing compared the produced body to the prior one: the renderer
and the adapter were tested in isolation, and the old test asserted the
placeholder itself.

SCOPE:
  1. _build_ship_pr_body's section 1 is the branch's own commits (subject +
     full body, oldest first), generated by clagentic-lite from git so tests
     assert on content, not on a vendor flag's semantics.
  2. End to end through cmd_ship with a stub host CLI that captures the body
     file: the captured body contains the commit text (the
     renderer-to-adapter seam that let this regress).
  3. Re-ship to an existing PR: the body is never edited; exactly one delta
     comment lists the commits added since the last ship, anchored by a
     hidden marker read back from the PR thread.
  4. Placeholder only when the range is genuinely empty or unresolvable.
  5. Truncation is bounded and explicit.

Every host interaction runs against a stateful stub `gh` on PATH -- no
network, no real host. This proves clagentic-lite's own output, not the
behavior of a real host (operator-side validation, see docs/GATES.md).

Run with: python3 -m unittest scripts.test_ship_commits_body -v
"""
import json
import os
import re
import shutil
import sqlite3
import stat
import subprocess
import sys
import tempfile
import textwrap
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from test_source_helpers import GATES_SH, HOST_ADAPTER_SH, PLATFORM_SH, SCRIPTS_DIR, source_env  # noqa: E402

_GIT_ENV = {
    "GIT_AUTHOR_NAME": "test", "GIT_AUTHOR_EMAIL": "test@example.com",
    "GIT_COMMITTER_NAME": "test", "GIT_COMMITTER_EMAIL": "test@example.com",
}

MARKER_RE = re.compile(r"<!-- clagentic-lite:shipped-head=([0-9a-f]{40,64}) -->")
BODY_HEADING = "## What changed and why"
NEXT_HEADING = "## Review provenance"


def _git(args, cwd):
    env = {**os.environ, **_GIT_ENV}
    return subprocess.run(["git"] + args, cwd=cwd, env=env, check=True,
                          capture_output=True, text=True, timeout=60).stdout.strip()


def _commit(repo, name, subject, body_lines=None):
    path = os.path.join(repo, name)
    with open(path, "a") as f:
        f.write("%s\n" % subject)
    _git(["add", name], repo)
    args = ["commit", "-q", "-m", subject]
    if body_lines:
        args += ["-m", "\n".join(body_lines)]
    _git(args, repo)
    return _git(["rev-parse", "HEAD"], repo)


def _empty_commit(repo, subject, body_lines=None):
    """A commit with no tree change: cheap enough to make hundreds."""
    # The message goes through a file: a multi-hundred-KB body would exceed the
    # per-argument limit of a -m argument.
    message = subject + ("\n\n" + "\n".join(body_lines) if body_lines else "") + "\n"
    with tempfile.NamedTemporaryFile("w", suffix=".msg", delete=False) as f:
        f.write(message)
    try:
        _git(["commit", "-q", "--allow-empty", "-F", f.name], repo)
    finally:
        os.unlink(f.name)
    return _git(["rev-parse", "HEAD"], repo)


def _make_repo(tmp, with_remote=True):
    """A repo on feat/example, one seed commit on main. With a remote: a
    local bare origin that already has main, so origin/main resolves."""
    repo = os.path.join(tmp, "repo")
    subprocess.run(["git", "init", "-q", "-b", "main", repo], check=True, timeout=60)
    _commit(repo, "seed.txt", "seed")
    if with_remote:
        bare = os.path.join(tmp, "origin.git")
        subprocess.run(["git", "init", "-q", "--bare", "-b", "main", bare], check=True, timeout=60)
        _git(["remote", "add", "origin", bare], repo)
        _git(["push", "-q", "origin", "main"], repo)
    _git(["checkout", "-q", "-b", "feat/example"], repo)
    return repo


THREE_COMMITS = [
    ("add parser", ["Parses the widget format.", "Handles empty input explicitly."]),
    ("wire parser into cli", ["Adds the --widget flag.", "", "Second paragraph of the body."]),
    ("document widget flag", ["## not a real heading, just body text", "Co-Authored-By: Someone <s@example.com>"]),
]


def _add_three_commits(repo):
    for i, (subject, body) in enumerate(THREE_COMMITS):
        _commit(repo, "f%d.txt" % i, subject, body)


def _call_build_ship_pr_body(repo, head, env_extra=None):
    env = os.environ.copy()
    env.update(source_env(gates=True))
    env["CLAGENTIC_PROJECT_ROOT"] = repo
    if env_extra:
        env.update(env_extra)
    script = ". '%s'\n_build_ship_pr_body 'feat/example' '%s'\n" % (GATES_SH, head)
    return subprocess.run(["sh", "-c", script, GATES_SH], capture_output=True, text=True,
                          env=env, cwd=repo, timeout=60)


def _section_one(body):
    start = body.index(BODY_HEADING) + len(BODY_HEADING)
    return body[start:body.index(NEXT_HEADING)]


def _sweep_for_pr_body_edits(root):
    """Return (tracked shell paths, [(path, line_no)] body-edit hits). Paths
    are repo-relative exactly as ls-files prints them and are opened under
    root as-is, so a script in a subdirectory is read, not skipped."""
    tracked = subprocess.run(["git", "-C", root, "ls-files", "*.sh"],
                             capture_output=True, text=True, check=True, timeout=30).stdout.split()
    hits = []
    for rel in tracked:
        with open(os.path.join(root, rel), encoding="utf-8") as f:
            lines = f.read().splitlines()
        for n, logical in _logical_lines(lines):
            if _line_edits_pr_body(logical):
                hits.append((rel, n))
    return tracked, hits


def _logical_lines(lines):
    """Yield (first_line_no, text) with backslash continuations joined and
    comment lines dropped, so `... api path \\` + `-X PATCH` is one line."""
    out, buf, start = [], "", 0
    for n, raw in enumerate(lines, 1):
        if not buf and raw.strip().startswith("#"):
            continue
        if not buf:
            start = n
        if raw.rstrip().endswith("\\"):
            buf += raw.rstrip()[:-1] + " "
            continue
        out.append((start, buf + raw))
        buf = ""
    if buf:
        out.append((start, buf))
    return out


_API_WORD = re.compile(r"\bapi\b")
_WRITE_VERB = re.compile(r"(?i:\bPATCH\b|\bPUT\b)|(?:^|\s)-X\s*\w*|--method\b")


def _line_edits_pr_body(line):
    """True for any shape that could rewrite a PR body: `pr edit` through any
    binary, a literal `gh api`, or an `api` subcommand through a variable- or
    path-named binary combined with PATCH/PUT, -X or --method."""
    if re.search(r"\bpr\s+edit\b", line) or re.search(r"\bgh\s+api\b", line):
        return True
    return bool(_API_WORD.search(line) and _WRITE_VERB.search(line))


_FAKE_GH = textwrap.dedent('''\
    #!/usr/bin/env python3
    import json, os, sys

    state_path = os.environ["FAKE_GH_STATE"]
    argv = sys.argv[1:]
    sys.path.insert(0, os.environ["FAKE_GH_GUARD_DIR"])
    import gh_stub_guard
    gh_stub_guard.check(argv)
    with open(state_path) as f:
        st = json.load(f)
    st["calls"].append(argv)

    def save():
        with open(state_path, "w") as f:
            json.dump(st, f)

    def body_file():
        with open(argv[argv.index("--body-file") + 1]) as f:
            return f.read()

    OPEN_NUMBER, CLOSED_NUMBER = "7", "3"

    def target_is_closed():
        # A numeric ref addresses exactly one PR. A bare branch name is
        # ambiguous when a closed and an open PR share it; the stub resolves
        # it to the CLOSED one, the wrong-PR hazard being guarded against.
        ref = argv[2]
        if ref == CLOSED_NUMBER:
            return True
        if ref == OPEN_NUMBER:
            return False
        return bool(st.get("closed_pr"))

    rc = 0
    if argv[:2] == ["pr", "view"] and "--json" in argv:
        if st.get("read_fail"):
            sys.stderr.write("simulated read failure\\n")
            rc = 1
        elif target_is_closed():
            print(st.get("closed_body", ""))
            for c in st.get("closed_comments", []):
                print(c)
        else:
            print(st["body"])
            for c in st["comments"]:
                print(c)
    elif argv[:2] == ["pr", "list"]:
        # Open-PR lookup honoring --state (default open), modelling one open
        # PR (number 7, when "exists") and one closed PR (number 3, when
        # "closed_pr") on the same branch.
        if st.get("list_fail"):
            sys.stderr.write("simulated transient host failure\\n")
            rc = 1
        else:
            wanted = argv[argv.index("--state") + 1] if "--state" in argv else "open"
            def flag(name):
                return argv[argv.index(name) + 1] if name in argv else None
            # Every open PR carries its own head and base, and --head/--base
            # filter on them the way the real CLI does. The main open PR is
            # number 7 (head/base default to the ship's, overridable); more
            # open PRs come from "extra_open" as {number, head, base}.
            open_prs = []
            if st["exists"]:
                open_prs.append({"number": OPEN_NUMBER, "head": st.get("open_head", "feat/example"),
                                 "base": st.get("open_base", "main")})
            open_prs.extend(st.get("extra_open", []))
            # A fork PR ("cross": true) shares the head branch NAME; it is
            # dropped only when the caller asked for isCrossRepository in
            # --json and filters on it in --jq, as the real CLI would.
            drops_cross = "isCrossRepository" in (flag("--json") or "") and \\
                "isCrossRepository == false" in (flag("--jq") or "")
            numbers = []
            if wanted in ("open", "all"):
                numbers += [p["number"] for p in open_prs
                            if flag("--head") in (None, p["head"]) and flag("--base") in (None, p["base"])
                            and not (drops_cross and p.get("cross"))]
            if st.get("closed_pr") and wanted in ("closed", "all"):
                numbers.append(CLOSED_NUMBER)
            # One number per line, as the adapter's jq prints them.
            for n in numbers:
                print(n)
    elif argv[:2] == ["pr", "view"]:
        # Bare view matches closed/merged PRs too, as the real CLI does.
        rc = 0 if (st["exists"] or st.get("closed_pr")) else 1
    elif argv[:2] == ["pr", "create"] and st.get("create_conflict"):
        # Another actor opened the PR between our lookup and this create.
        sys.stderr.write("a pull request for this branch already exists\\n")
        rc = 1
    elif argv[:2] == ["pr", "create"]:
        st["exists"] = True
        st["body"] = body_file() if "--body-file" in argv else ""
        st["created_bodies"].append(st["body"])
        print("https://github.com/example/example/pull/" + OPEN_NUMBER)
    elif argv[:2] == ["pr", "comment"]:
        key = "closed_comments" if target_is_closed() else "comments"
        st.setdefault(key, []).append(body_file())
    save()
    sys.exit(rc)
''')


class _Env:
    """Temp dir + repo + stub gh + audit db, torn down by the test."""

    def __init__(self, test, with_remote=True):
        self.tmp = tempfile.mkdtemp(prefix="clagentic-test-ship-commits-")
        test.addCleanup(shutil.rmtree, self.tmp, ignore_errors=True)
        self.repo = _make_repo(self.tmp, with_remote=with_remote)
        self.bin = os.path.join(self.tmp, "bin")
        os.makedirs(self.bin)
        gh = os.path.join(self.bin, "gh")
        with open(gh, "w") as f:
            f.write(_FAKE_GH)
        os.chmod(gh, stat.S_IRWXU)
        self.state_path = os.path.join(self.tmp, "gh-state.json")
        self.set_state(exists=False, body="", comments=[], calls=[], created_bodies=[],
                       read_fail=False, list_fail=False, closed_pr=False, create_conflict=False)

    def set_state(self, **kw):
        st = self.state() if os.path.exists(self.state_path) else {}
        st.update(kw)
        with open(self.state_path, "w") as f:
            json.dump(st, f)

    def state(self):
        with open(self.state_path) as f:
            return json.load(f)

    def ship(self):
        env = os.environ.copy()
        env.update({
            "CLAGENTIC_PROJECT_ROOT": self.repo,
            "CLAGENTIC_GATES": "none",
            "CLAGENTIC_REPO_HOST": "github",
            "FAKE_GH_STATE": self.state_path,
            "FAKE_GH_GUARD_DIR": os.path.dirname(os.path.abspath(__file__)),
            "HOME": self.tmp,
            "PATH": self.bin + os.pathsep + env.get("PATH", ""),
        })
        r = subprocess.run(["sh", GATES_SH, "ship"], cwd=self.repo, env=env,
                           capture_output=True, text=True, timeout=180)
        return r

    def calls(self):
        return [" ".join(c) for c in self.state()["calls"]]

    def audit_rows(self, gate):
        db = os.path.join(self.repo, ".clagentic", "lite", "audit.db")
        conn = sqlite3.connect(db)
        try:
            return conn.execute("SELECT outcome, details FROM gate_runs WHERE gate=?", (gate,)).fetchall()
        finally:
            conn.close()


class TestBuildShipPrBodyCarriesCommits(unittest.TestCase):
    def test_every_subject_and_body_line_appears_oldest_first(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        head = _git(["rev-parse", "HEAD"], e.repo)
        r = _call_build_ship_pr_body(e.repo, head)
        self.assertEqual(r.returncode, 0, r.stderr)
        section = _section_one(r.stdout)
        last = -1
        for subject, body in THREE_COMMITS:
            pos = section.index(subject)
            self.assertGreater(pos, last, "commits must be listed oldest first")
            last = pos
            # The whole body, blank lines included, so a lost paragraph
            # boundary fails.
            whole = "\n".join(("  " + l) if l else "" for l in body)
            self.assertIn(whole + "\n", section)

    def test_false_summarizer_claim_is_gone(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        r = _call_build_ship_pr_body(e.repo, _git(["rev-parse", "HEAD"], e.repo))
        self.assertNotIn("summarizer", r.stdout)

    def test_body_ends_with_marker_for_shipped_head(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        head = _git(["rev-parse", "HEAD"], e.repo)
        r = _call_build_ship_pr_body(e.repo, head)
        self.assertEqual(MARKER_RE.findall(r.stdout), [head])

    def test_merge_commits_are_not_listed(self):
        e = _Env(self)
        _commit(e.repo, "a.txt", "feature work")
        _git(["checkout", "-q", "-b", "side", "main"], e.repo)
        _commit(e.repo, "b.txt", "side work")
        _git(["checkout", "-q", "feat/example"], e.repo)
        _git(["merge", "-q", "--no-ff", "-m", "Merge branch side", "side"], e.repo)
        r = _call_build_ship_pr_body(e.repo, _git(["rev-parse", "HEAD"], e.repo))
        section = _section_one(r.stdout)
        self.assertIn("feature work", section)
        self.assertIn("side work", section)
        self.assertNotIn("Merge branch side", section)


def _criss_cross(repo):
    """main and feat/example each merge the other's side, so their tips have two
    merge-bases (a and b). Then main gains an upstream commit and feat gains a
    branch commit. Returns the feat head."""
    _git(["checkout", "-q", "-b", "side-a", "main"], repo)
    _commit(repo, "a.txt", "upstream commit a")
    _git(["checkout", "-q", "feat/example"], repo)
    _commit(repo, "b.txt", "branch commit b")
    _git(["checkout", "-q", "-b", "side-b"], repo)
    _git(["checkout", "-q", "main"], repo)
    _git(["merge", "-q", "--no-ff", "-m", "main takes b", "side-b"], repo)
    _git(["merge", "-q", "--no-ff", "-m", "main takes a", "side-a"], repo)
    _commit(repo, "u1.txt", "upstream commit u1")
    _git(["push", "-q", "origin", "main"], repo)
    _git(["checkout", "-q", "feat/example"], repo)
    _git(["merge", "-q", "--no-ff", "-m", "feat takes a", "side-a"], repo)
    return _git(["rev-parse", "HEAD"], repo)


class TestOneRangePrimitiveForBodyAndDelta(unittest.TestCase):
    def test_body_after_merging_the_default_tip_lists_only_branch_commits(self):
        e = _Env(self)
        _commit(e.repo, "f0.txt", "branch commit before merge")
        _git(["checkout", "-q", "main"], e.repo)
        _commit(e.repo, "up1.txt", "upstream change one")
        _git(["push", "-q", "origin", "main"], e.repo)
        _git(["checkout", "-q", "feat/example"], e.repo)
        _git(["merge", "-q", "--no-ff", "-m", "merge main into feat", "main"], e.repo)
        _commit(e.repo, "f1.txt", "branch commit after merge")
        r = _call_build_ship_pr_body(e.repo, _git(["rev-parse", "HEAD"], e.repo))
        self.assertEqual(r.returncode, 0, r.stderr)
        section = _section_one(r.stdout)
        self.assertIn("branch commit before merge", section)
        self.assertIn("branch commit after merge", section)
        self.assertNotIn("upstream change one", section)

    def test_criss_cross_merge_lists_no_upstream_commit_in_body_or_delta(self):
        e = _Env(self)
        head = _criss_cross(e.repo)
        self.assertEqual(len(_git(["merge-base", "--all", "origin/main", head], e.repo).split()), 2)
        r = _call_build_ship_pr_body(e.repo, head)
        self.assertEqual(r.returncode, 0, r.stderr)
        section = _section_one(r.stdout)
        self.assertNotIn("upstream commit", section)

        self.assertEqual(e.ship().returncode, 0)
        _commit(e.repo, "f9.txt", "branch commit after criss-cross")
        r = e.ship()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        comments = e.state()["comments"]
        self.assertEqual(len(comments), 1)
        self.assertIn("branch commit after criss-cross", comments[0])
        self.assertNotIn("upstream commit", comments[0])


class TestPlaceholderOnlyWhenRangeUnavailable(unittest.TestCase):
    PLACEHOLDER_MARKERS = ("Commit list unavailable", "No commits to list")

    def test_no_placeholder_when_commits_exist(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        r = _call_build_ship_pr_body(e.repo, _git(["rev-parse", "HEAD"], e.repo))
        for m in self.PLACEHOLDER_MARKERS:
            self.assertNotIn(m, r.stdout)

    def test_unresolvable_range_states_the_actual_reason(self):
        e = _Env(self, with_remote=False)
        _add_three_commits(e.repo)
        r = _call_build_ship_pr_body(e.repo, _git(["rev-parse", "HEAD"], e.repo))
        section = _section_one(r.stdout)
        self.assertIn("Commit list unavailable", section)
        self.assertIn("the default branch tip could not be resolved or proven current", section)

    def test_empty_range_says_so(self):
        e = _Env(self)
        r = _call_build_ship_pr_body(e.repo, _git(["rev-parse", "HEAD"], e.repo))
        section = _section_one(r.stdout)
        self.assertIn("No commits to list", section)
        self.assertNotIn("Commit list unavailable", section)

    def test_unresolved_head_states_the_actual_reason(self):
        e = _Env(self)
        r = _call_build_ship_pr_body(e.repo, "")
        self.assertIn("the shipped head commit could not be resolved", _section_one(r.stdout))
        self.assertEqual(MARKER_RE.findall(r.stdout), [])

    def test_no_marker_when_base_is_unresolved(self):
        e = _Env(self, with_remote=False)
        _add_three_commits(e.repo)
        r = _call_build_ship_pr_body(e.repo, _git(["rev-parse", "HEAD"], e.repo))
        self.assertIn("Commit list unavailable", r.stdout)
        self.assertEqual(MARKER_RE.findall(r.stdout), [],
                         "a marker for a head whose commits were never listed hides them from later ships")

    def test_no_marker_when_range_is_empty(self):
        e = _Env(self)
        r = _call_build_ship_pr_body(e.repo, _git(["rev-parse", "HEAD"], e.repo))
        self.assertIn("No commits to list", r.stdout)
        self.assertEqual(MARKER_RE.findall(r.stdout), [])


class TestCommitBodyCannotBecomeMarkdownStructure(unittest.TestCase):
    HOSTILE = ["## X", "```", "injected after a fence", "````", "# Another", "---"]

    def test_hostile_body_is_confined_to_a_fence_longer_than_any_backtick_run(self):
        e = _Env(self)
        _commit(e.repo, "h.txt", "hostile body", self.HOSTILE)
        _commit(e.repo, "i.txt", "innocent follow-up", ["plain text"])
        r = _call_build_ship_pr_body(e.repo, _git(["rev-parse", "HEAD"], e.repo))
        self.assertEqual(r.returncode, 0, r.stderr)
        section = _section_one(r.stdout)
        lines = section.split("\n")
        fence_re = re.compile(r"^ {2}(`{3,})$")
        fences = [(i, fence_re.match(l).group(1)) for i, l in enumerate(lines) if fence_re.match(l)]
        open_i, open_f = fences[0]
        self.assertGreater(len(open_f), 4, "fence must outrun the longest backtick run (4) in the body")
        # The first line that can close the fence is the first one at least as
        # long as the opener; the body's own 3- and 4-backtick lines cannot.
        close_i = next(i for i, f in fences[1:] if len(f) >= len(open_f))
        self.assertEqual(lines[close_i].strip(), open_f)
        inside = lines[open_i + 1:close_i]
        self.assertIn("  ```", inside)
        self.assertIn("  # Another", inside)
        self.assertIn("  ## X", inside)
        self.assertIn("  injected after a fence", inside)
        self.assertEqual([l for l in lines[:open_i] if l.startswith("#")], [])
        self.assertIn("innocent follow-up", section)
        self.assertIn(NEXT_HEADING, r.stdout)


class TestSubjectCannotHideLaterCommits(unittest.TestCase):
    SUBJECTS = ["open <!-- never closed", "\\<!-- already backslashed", "## X heading",
                "tick ` and ``` runs", "later commit stays visible"]

    def test_subject_markup_is_confined_to_the_commit_fence(self):
        e = _Env(self)
        for i, subject in enumerate(self.SUBJECTS):
            _commit(e.repo, "s%d.txt" % i, subject, ["body of %d" % i])
        r = _call_build_ship_pr_body(e.repo, _git(["rev-parse", "HEAD"], e.repo))
        self.assertEqual(r.returncode, 0, r.stderr)
        section = _section_one(r.stdout)
        lines = section.split("\n")
        fence_re = re.compile(r"^ {2}(`{3,})$")
        in_fence, opener, seen = False, "", []
        for line in lines:
            m = fence_re.match(line)
            if not in_fence and m:
                in_fence, opener = True, m.group(1)
            elif in_fence and m and len(m.group(1)) >= len(opener):
                in_fence = False
            elif in_fence:
                seen.append(line)
            elif line.strip():
                self.assertRegex(line, r"^- `[0-9a-f]{7}`$|^\s*<!-- clagentic-lite:shipped-head=", line)
        for subject in self.SUBJECTS:
            self.assertIn("  " + subject, seen)
        self.assertFalse(in_fence, "every fence is closed")
        self.assertEqual(MARKER_RE.findall(r.stdout), [_git(["rev-parse", "HEAD"], e.repo)])


class TestRendererFailureNeverLeavesABareHeading(unittest.TestCase):
    def _body_with_section_stub(self, e, stub):
        env = os.environ.copy()
        env.update(source_env(gates=True))
        env["CLAGENTIC_PROJECT_ROOT"] = e.repo
        head = _git(["rev-parse", "HEAD"], e.repo)
        script = ". '%s'\n%s\n_build_ship_pr_body 'feat/example' '%s'\n" % (GATES_SH, stub, head)
        return subprocess.run(["sh", "-c", script, GATES_SH], capture_output=True, text=True,
                              env=env, cwd=e.repo, timeout=60)

    def test_failing_section_renderer_yields_the_placeholder(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        r = self._body_with_section_stub(e, "_ship_render_commits_section() { return 1; }")
        self.assertEqual(r.returncode, 0, r.stderr)
        section = _section_one(r.stdout)
        self.assertIn("Commit list unavailable: the commit list could not be rendered", section)
        self.assertEqual(MARKER_RE.findall(r.stdout), [])

    def test_silent_section_renderer_yields_the_placeholder(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        r = self._body_with_section_stub(e, "_ship_render_commits_section() { return 0; }")
        self.assertIn("Commit list unavailable", _section_one(r.stdout))

    def test_failing_bounder_yields_fixed_placeholders_not_bare_headings(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        r = self._body_with_section_stub(e, "_ship_bound_text() { return 1; }")
        self.assertEqual(r.returncode, 0, r.stderr)
        body = r.stdout
        review = body[body.index("## Review provenance"):body.index("## Gate attestation")]
        attest = body[body.index("## Gate attestation"):body.index("## Trade-offs")]
        self.assertIn("review section could not be rendered", review)
        self.assertIn("gate attestation could not be rendered", attest)

    def test_failing_enumeration_is_never_blank(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        r = self._body_with_section_stub(e, "_git() { return 1; }")
        self.assertTrue(_section_one(r.stdout).strip(), "section must never be blank")


class TestBaseResolverStderrIsNotPartOfTheRef(unittest.TestCase):
    def test_resolver_warning_on_stderr_still_yields_a_correct_commit_list(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        head = _git(["rev-parse", "HEAD"], e.repo)
        main_tip = _git(["rev-parse", "main"], e.repo)
        env = os.environ.copy()
        env.update(source_env(gates=True))
        env["CLAGENTIC_PROJECT_ROOT"] = e.repo
        script = textwrap.dedent("""\
            . '%s'
            _gate_resolve_fresh_default_branch_ref() {
              echo "WARN: something noisy on stderr" 1>&2
              printf '%%s\\n' '%s'
            }
            _build_ship_pr_body 'feat/example' '%s'
        """) % (GATES_SH, main_tip, head)
        r = subprocess.run(["sh", "-c", script, GATES_SH], capture_output=True, text=True,
                           env=env, cwd=e.repo, timeout=60)
        self.assertEqual(r.returncode, 0, r.stderr)
        section = _section_one(r.stdout)
        self.assertNotIn("Commit list unavailable", section)
        self.assertNotIn("WARN", r.stdout)
        for subject, _ in THREE_COMMITS:
            self.assertIn(subject, section)


class TestPublicReasonIsFixedString(unittest.TestCase):
    def test_resolver_stderr_never_reaches_the_body(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        head = _git(["rev-parse", "HEAD"], e.repo)
        env = os.environ.copy()
        env.update(source_env(gates=True))
        env["CLAGENTIC_PROJECT_ROOT"] = e.repo
        script = textwrap.dedent("""\
            . '%s'
            _gate_resolve_fresh_default_branch_ref() {
              echo "fatal: unable to access /home/secretuser/internal.example.org" 1>&2
              return 1
            }
            _build_ship_pr_body 'feat/example' '%s'
        """) % (GATES_SH, head)
        r = subprocess.run(["sh", "-c", script, GATES_SH], capture_output=True, text=True,
                           env=env, cwd=e.repo, timeout=60)
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("the default branch tip could not be resolved or proven current", r.stdout)
        self.assertNotIn("secretuser", r.stdout)
        self.assertNotIn("internal.example.org", r.stdout)
        self.assertIn("secretuser", r.stderr, "raw detail stays on the local stderr")


HOST_LIMIT = 65536
TRUNC_NOTE_RE = re.compile(r"\[commit message truncated, (\d+) chars not shown\]")
LISTED_SUBJECT_RE = r"^  commit number \d+$"


class TestTruncation(unittest.TestCase):
    def test_oversize_range_is_bounded_with_explicit_count_and_marks_head(self):
        e = _Env(self)
        for i in range(10):
            _commit(e.repo, "f%d.txt" % i, "commit number %d" % i, ["x" * 300])
        head = _git(["rev-parse", "HEAD"], e.repo)
        r = _call_build_ship_pr_body(e.repo, head, {"CLAGENTIC_SHIP_COMMITS_MAX_CHARS": "1500"})
        self.assertEqual(r.returncode, 0, r.stderr)
        section = _section_one(r.stdout)
        shown = len(re.findall(LISTED_SUBJECT_RE, section, re.M))
        m = re.search(r"_(\d+) more commits not shown -- see this PR's Commits tab\._", section)
        self.assertIsNotNone(m, "truncation must be explicit, never silent")
        self.assertTrue(0 < shown < 10)
        self.assertEqual(shown + int(m.group(1)), 10)
        self.assertLessEqual(len(section.strip()), 1500, "the configured cap bounds the whole list block")
        self.assertIn("  commit number 0\n", section, "oldest commits are the ones kept")
        self.assertEqual(MARKER_RE.findall(r.stdout), [head], "the marker is always HEAD")

    def test_uncapped_body_has_no_not_shown_line(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        r = _call_build_ship_pr_body(e.repo, _git(["rev-parse", "HEAD"], e.repo))
        self.assertNotIn("not shown", r.stdout)

    def test_single_oversize_commit_message_is_cut_with_explicit_count(self):
        e = _Env(self)
        _commit(e.repo, "big.txt", "huge commit", ["line %d %s" % (i, "y" * 40) for i in range(200)])
        head = _git(["rev-parse", "HEAD"], e.repo)
        r = _call_build_ship_pr_body(e.repo, head, {"CLAGENTIC_SHIP_COMMITS_MAX_CHARS": "1000"})
        section = _section_one(r.stdout)
        self.assertIn("huge commit", section)
        self.assertRegex(section, TRUNC_NOTE_RE)
        self.assertLessEqual(len(section.strip()), 1000)

    def test_cap_below_one_entry_lists_nothing_and_says_why(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        head = _git(["rev-parse", "HEAD"], e.repo)
        r = _call_build_ship_pr_body(e.repo, head, {"CLAGENTIC_SHIP_COMMITS_MAX_CHARS": "100"})
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("Commit list omitted", _section_one(r.stdout))
        self.assertEqual(MARKER_RE.findall(r.stdout), [], "an unlisted head must not be anchored")


class TestWholeArtifactWithinHostLimit(unittest.TestCase):
    """The host hard limit applies to the WHOLE body and the WHOLE comment,
    not to the commit list alone: fixed headings, review provenance, the
    attestation, placeholders and the marker all count."""

    def _body(self, e, env_extra=None):
        head = _git(["rev-parse", "HEAD"], e.repo)
        r = _call_build_ship_pr_body(e.repo, head, env_extra)
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertLessEqual(len(r.stdout), HOST_LIMIT, "whole body over the host limit")
        return head, r.stdout

    def test_single_giant_commit_message(self):
        e = _Env(self)
        _empty_commit(e.repo, "giant", ["line %d %s" % (i, "z" * 50) for i in range(5000)])
        head, body = self._body(e)
        m = TRUNC_NOTE_RE.search(body)
        self.assertIsNotNone(m, "a cut message must say so")
        self.assertGreater(int(m.group(1)), 0)
        self.assertIn("  giant\n", body)
        self.assertEqual(MARKER_RE.findall(body), [head], "a truncated entry counts as listed")

    def test_giant_single_line_body(self):
        e = _Env(self)
        _empty_commit(e.repo, "one long line", ["q" * 120000])
        head, body = self._body(e)
        self.assertRegex(body, TRUNC_NOTE_RE)
        self.assertEqual(MARKER_RE.findall(body), [head])

    def test_giant_subject(self):
        e = _Env(self)
        _empty_commit(e.repo, "S" * 100000, ["a short body"])
        head, body = self._body(e)
        self.assertRegex(body, TRUNC_NOTE_RE)
        self.assertIn("  SSSS", body)
        self.assertEqual(MARKER_RE.findall(body), [head])

    def test_many_commits(self):
        e = _Env(self)
        for i in range(300):
            _empty_commit(e.repo, "commit number %d" % i, ["w" * 300])
        head, body = self._body(e)
        shown = len(re.findall(LISTED_SUBJECT_RE, body, re.M))
        m = re.search(r"_(\d+) more commits not shown", body)
        self.assertIsNotNone(m)
        self.assertEqual(shown + int(m.group(1)), 300)

    def test_configured_cap_cannot_raise_the_budget_past_the_limit(self):
        e = _Env(self)
        for i in range(300):
            _empty_commit(e.repo, "commit number %d" % i, ["w" * 300])
        self._body(e, {"CLAGENTIC_SHIP_COMMITS_MAX_CHARS": "999999999"})

    def test_oversized_review_provenance_is_bounded_and_commits_still_listed(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        head = _git(["rev-parse", "HEAD"], e.repo)
        findings = [{"severity": "high", "file": "f%d.py" % i, "line": 1, "category": "x",
                     "message": "m%d %s" % (i, "r" * 3000), "_ledger_recurring": True} for i in range(80)]
        ledger_dir = os.path.join(e.repo, ".clagentic", "lite")
        os.makedirs(ledger_dir, exist_ok=True)
        with open(os.path.join(ledger_dir, "review-ledger.jsonl"), "w") as f:
            f.write(json.dumps({"ts": "2026-08-18T00:00:00Z", "branch": "feat/example", "base_sha": "",
                                "head_sha": head, "verdict": "block", "findings": findings,
                                "config": {}}) + "\n")
        _, body = self._body(e)
        self.assertRegex(body, r"\[truncated, \d+ chars not shown\]")
        for subject, _ in THREE_COMMITS:
            self.assertIn(subject, body)
        self.assertEqual(MARKER_RE.findall(body), [head])

    def test_final_guard_shrinks_a_list_that_ignores_its_budget(self):
        """Even a list renderer that overruns the budget it was given cannot
        produce an over-limit body: the whole-artifact guard re-budgets."""
        e = _Env(self)
        _add_three_commits(e.repo)
        head = _git(["rev-parse", "HEAD"], e.repo)
        env = os.environ.copy()
        env.update(source_env(gates=True))
        env["CLAGENTIC_PROJECT_ROOT"] = e.repo
        script = textwrap.dedent("""\
            . '%s'
            _ship_render_commit_list() {
              head -c "$(( $3 + 1000 ))" /dev/zero | tr '\\0' x
              printf '\\n'
              _ship_marker_line '%s'
            }
            _build_ship_pr_body 'feat/example' '%s'
        """) % (GATES_SH, head, head)
        r = subprocess.run(["sh", "-c", script, GATES_SH], capture_output=True, text=True,
                           env=env, cwd=e.repo, timeout=60)
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertLessEqual(len(r.stdout), HOST_LIMIT)
        self.assertIn(NEXT_HEADING, r.stdout)

    def test_a_body_that_cannot_be_made_to_fit_is_never_emitted(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        head = _git(["rev-parse", "HEAD"], e.repo)
        env = os.environ.copy()
        env.update(source_env(gates=True))
        env["CLAGENTIC_PROJECT_ROOT"] = e.repo
        script = textwrap.dedent("""\
            . '%s'
            _ship_render_commit_list() { head -c 90000 /dev/zero | tr '\\0' x; }
            _build_ship_pr_body 'feat/example' '%s'
        """) % (GATES_SH, head)
        r = subprocess.run(["sh", "-c", script, GATES_SH], capture_output=True, text=True,
                           env=env, cwd=e.repo, timeout=60)
        self.assertNotEqual(r.returncode, 0)
        self.assertEqual(r.stdout, "")

    def test_delta_comment_for_many_commits_is_within_the_limit(self):
        e = _Env(self)
        for i in range(300):
            _empty_commit(e.repo, "commit number %d" % i, ["w" * 300])
        e.set_state(exists=True, body="hand-written description, no marker")
        r = e.ship()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        comments = e.state()["comments"]
        self.assertEqual(len(comments), 1)
        self.assertLessEqual(len(comments[0]), HOST_LIMIT, "whole comment over the host limit")
        self.assertRegex(comments[0], r"_\d+ more commits not shown")

    def test_delta_comment_for_a_giant_message_is_within_the_limit(self):
        e = _Env(self)
        _empty_commit(e.repo, "G" * 100000, ["line %d %s" % (i, "z" * 50) for i in range(5000)])
        head = _git(["rev-parse", "HEAD"], e.repo)
        e.set_state(exists=True, body="hand-written description, no marker")
        r = e.ship()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        comments = e.state()["comments"]
        self.assertEqual(len(comments), 1)
        self.assertLessEqual(len(comments[0]), HOST_LIMIT)
        self.assertRegex(comments[0], TRUNC_NOTE_RE)
        self.assertEqual(MARKER_RE.findall(comments[0]), [head])

    def test_giant_first_commit_is_truncated_and_the_rest_are_counted_not_shown(self):
        e = _Env(self)
        _empty_commit(e.repo, "giant first", ["line %d %s" % (i, "z" * 50) for i in range(5000)])
        _empty_commit(e.repo, "small second", ["tiny " * 120])
        self.assertEqual(e.ship().returncode, 0)
        created = e.state()["created_bodies"][0]
        self.assertLessEqual(len(created), HOST_LIMIT)
        self.assertIn("  giant first\n", created)
        self.assertNotIn("small second", created)
        self.assertIn("1 more commits not shown -- see this PR's Commits tab.", created)
        self.assertEqual(e.ship().returncode, 0)
        self.assertEqual(e.state()["comments"], [], "an unchanged re-ship never pages the rest in")


class TestShipEndToEnd(unittest.TestCase):
    def test_created_body_captured_by_stub_contains_commit_text(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        r = e.ship()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        created = e.state()["created_bodies"]
        self.assertEqual(len(created), 1)
        for subject, body in THREE_COMMITS:
            self.assertIn(subject, created[0])
            for line in body:
                if line:
                    self.assertIn(line, created[0])
        self.assertEqual(MARKER_RE.findall(created[0]), [_git(["rev-parse", "HEAD"], e.repo)])
        self.assertEqual(e.state()["comments"], [], "a fresh PR gets a body, not a comment")

    def test_reship_with_new_commit_posts_one_comment_and_never_edits_body(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        self.assertEqual(e.ship().returncode, 0)
        original_body = e.state()["body"]
        e.set_state(calls=[])

        _commit(e.repo, "f9.txt", "fix off-by-one in parser", ["Found while reviewing."])
        new_head = _git(["rev-parse", "HEAD"], e.repo)
        r = e.ship()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)

        calls = e.calls()
        self.assertEqual([c for c in calls if c.startswith("pr create")], [])
        self.assertEqual(len([c for c in calls if c.startswith("pr comment")]), 1, calls)
        for c in calls:
            self.assertFalse(c.startswith("pr edit"), "no code path may edit a PR body: %r" % c)
            self.assertFalse(c.startswith("api"), c)
            if not c.startswith("pr comment"):
                self.assertNotIn("--body", c)
        st = e.state()
        self.assertEqual(st["body"], original_body, "body must be untouched on re-ship")
        comment = st["comments"][0]
        self.assertIn("fix off-by-one in parser", comment)
        self.assertIn("Found while reviewing.", comment)
        for subject, _ in THREE_COMMITS:
            self.assertNotIn(subject, comment, "only post-marker commits belong in the delta")
        self.assertEqual(MARKER_RE.findall(comment), [new_head])

    def test_reship_with_no_new_commits_posts_nothing(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        self.assertEqual(e.ship().returncode, 0)
        e.set_state(calls=[])
        r = e.ship()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        self.assertEqual([c for c in e.calls() if c.startswith("pr comment")], [])
        self.assertEqual(e.state()["comments"], [])

    def test_reship_after_merging_the_default_branch_lists_only_branch_commits(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        self.assertEqual(e.ship().returncode, 0)

        _git(["checkout", "-q", "main"], e.repo)
        _commit(e.repo, "up1.txt", "upstream change one")
        _commit(e.repo, "up2.txt", "upstream change two")
        _git(["push", "-q", "origin", "main"], e.repo)
        _git(["checkout", "-q", "feat/example"], e.repo)
        _git(["merge", "-q", "--no-ff", "-m", "merge main into feat/example", "main"], e.repo)
        _commit(e.repo, "f9.txt", "branch commit after the merge")
        e.set_state(calls=[])

        r = e.ship()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        comments = e.state()["comments"]
        self.assertEqual(len(comments), 1)
        self.assertIn("branch commit after the merge", comments[0])
        self.assertNotIn("upstream change", comments[0], "upstream commits carried by the merge are not this branch's")

    def test_unchanged_reships_with_a_merged_side_branch_post_nothing(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        _git(["checkout", "-q", "-b", "side/a"], e.repo)
        _commit(e.repo, "side.txt", "side branch commit A")
        _git(["checkout", "-q", "feat/example"], e.repo)
        _commit(e.repo, "f9.txt", "feature commit B")
        _git(["merge", "-q", "--no-ff", "-m", "merge side/a", "side/a"], e.repo)
        self.assertEqual(e.ship().returncode, 0)
        for _ in range(2):
            r = e.ship()
            self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
            self.assertEqual(e.state()["comments"], [], "nothing new -> nothing posted")

    def test_unchanged_reships_after_merging_the_default_branch_in_post_nothing(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        self.assertEqual(e.ship().returncode, 0)
        _git(["checkout", "-q", "main"], e.repo)
        _commit(e.repo, "up1.txt", "upstream change one")
        _git(["push", "-q", "origin", "main"], e.repo)
        _git(["checkout", "-q", "feat/example"], e.repo)
        _git(["merge", "-q", "--no-ff", "-m", "merge main into feat/example", "main"], e.repo)
        for _ in range(2):
            r = e.ship()
            self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
            self.assertEqual(e.state()["comments"], [], "a merge of main adds no branch commit")

    def test_capped_reship_lists_exactly_the_new_commits(self):
        e = _Env(self)
        for i in range(10):
            _commit(e.repo, "f%d.txt" % i, "commit number %d" % i, ["x" * 300])
        old = os.environ.get("CLAGENTIC_SHIP_COMMITS_MAX_CHARS")
        os.environ["CLAGENTIC_SHIP_COMMITS_MAX_CHARS"] = "1500"
        try:
            self.assertEqual(e.ship().returncode, 0)
            self.assertIn("more commits not shown", e.state()["created_bodies"][0])
            for i in (10, 11):
                _commit(e.repo, "g%d.txt" % i, "fresh commit %d" % i)
            new_head = _git(["rev-parse", "HEAD"], e.repo)
            self.assertEqual(e.ship().returncode, 0)
        finally:
            if old is None:
                os.environ.pop("CLAGENTIC_SHIP_COMMITS_MAX_CHARS", None)
            else:
                os.environ["CLAGENTIC_SHIP_COMMITS_MAX_CHARS"] = old
        comments = e.state()["comments"]
        self.assertEqual(len(comments), 1)
        self.assertEqual(re.findall(r"^  (fresh commit \d+)$", comments[0], re.M),
                         ["fresh commit 10", "fresh commit 11"])
        self.assertNotIn("commit number", comments[0])
        self.assertEqual(MARKER_RE.findall(comments[0]), [new_head])

    def test_ship_prints_the_pr_number_when_created_and_when_reused(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        created = e.ship()
        self.assertEqual(created.returncode, 0, created.stdout + created.stderr)
        self.assertIn("PR #7 created", created.stdout)
        reused = e.ship()
        self.assertEqual(reused.returncode, 0, reused.stdout + reused.stderr)
        self.assertIn("PR #7 already open", reused.stdout)

    def test_third_ship_anchors_on_the_newest_marker_in_a_comment(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        self.assertEqual(e.ship().returncode, 0)
        _commit(e.repo, "g1.txt", "second wave one")
        self.assertEqual(e.ship().returncode, 0)
        _commit(e.repo, "g2.txt", "third wave two")
        self.assertEqual(e.ship().returncode, 0)
        comments = e.state()["comments"]
        self.assertEqual(len(comments), 2)
        self.assertIn("third wave two", comments[1])
        self.assertNotIn("second wave one", comments[1])

    def test_rewritten_history_posts_full_list_with_reason(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        self.assertEqual(e.ship().returncode, 0)
        _git(["commit", "-q", "--amend", "-m", "document widget flag (reworded)"], e.repo)
        _git(["push", "-q", "-f", "origin", "feat/example"], e.repo)
        e.set_state(calls=[])
        r = e.ship()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        comments = e.state()["comments"]
        self.assertEqual(len(comments), 1)
        self.assertIn("History was rewritten", comments[0])
        for subject, _ in THREE_COMMITS[:2]:
            self.assertIn(subject, comments[0])
        self.assertIn("document widget flag (reworded)", comments[0])

    def test_pr_without_a_marker_gets_full_list_with_reason(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        e.set_state(exists=True, body="hand-written description, no marker")
        r = e.ship()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        comments = e.state()["comments"]
        self.assertEqual(len(comments), 1)
        self.assertIn("No earlier ship marker", comments[0])
        for subject, _ in THREE_COMMITS:
            self.assertIn(subject, comments[0])
        self.assertEqual(e.state()["body"], "hand-written description, no marker")

    def test_thread_read_failure_posts_nothing_and_is_audit_logged(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        e.set_state(exists=True, body="whatever", read_fail=True)
        r = e.ship()
        self.assertEqual(r.returncode, 0, "a publish problem must never block ship: " + r.stdout + r.stderr)
        self.assertEqual(e.state()["comments"], [])
        self.assertEqual([c for c in e.calls() if c.startswith("pr comment")], [])
        rows = e.audit_rows("ship-delta-publish")
        self.assertTrue(any(o == "block" and "thread-read-failed" in d for o, d in rows), rows)


class TestShipBoundText(unittest.TestCase):
    def _bound(self, limit, text):
        env = os.environ.copy()
        env.update(source_env(gates=True))
        script = ". '%s'\n_ship_bound_text %d \"$1\"\n" % (GATES_SH, limit)
        return subprocess.run(["sh", "-c", script, GATES_SH, text], capture_output=True,
                              text=True, env=env, timeout=60)

    def test_notice_counts_inside_the_limit(self):
        text = "\n".join("line %03d %s" % (i, "w" * 30) for i in range(40))
        r = self._bound(300, text)
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertRegex(r.stdout, r"\[truncated, \d+ chars not shown\]")
        self.assertLessEqual(len(r.stdout), 300)

    def test_limit_smaller_than_the_notice_omits_it_and_stays_within_limit(self):
        text = "\n".join("line %03d %s" % (i, "w" * 30) for i in range(40))
        for limit in (10, 25, 31):
            r = self._bound(limit, text)
            self.assertEqual(r.returncode, 0, r.stderr)
            self.assertNotIn("truncated", r.stdout)
            self.assertLessEqual(len(r.stdout), limit, (limit, r.stdout))


class TestShipPrLookupStates(unittest.TestCase):
    def test_same_head_pr_against_another_base_is_not_reused(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        e.set_state(exists=True, open_head="feat/example", open_base="develop")
        r = e.ship()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        st = e.state()
        self.assertEqual(len(st["created_bodies"]), 1, e.calls())
        self.assertEqual(st["comments"], [])
        lookups = [c for c in e.calls() if c.startswith("pr list")]
        self.assertTrue(all("--base main" in c for c in lookups), lookups)

    def test_closed_pr_for_a_reused_branch_creates_a_new_pr_and_posts_no_comment(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        e.set_state(closed_pr=True)
        r = e.ship()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        st = e.state()
        self.assertEqual(len(st["created_bodies"]), 1, e.calls())
        for subject, _ in THREE_COMMITS:
            self.assertIn(subject, st["created_bodies"][0])
        self.assertEqual(st["comments"], [])

    def test_closed_and_open_pr_on_one_branch_read_and_comment_target_the_open_number(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        self.assertEqual(e.ship().returncode, 0)
        # A stale CLOSED PR on the same branch whose thread carries no marker:
        # a wrong-PR read would find none and list the full range.
        e.set_state(closed_pr=True, closed_body="old PR, no marker", closed_comments=[], calls=[])
        _commit(e.repo, "f9.txt", "fix off-by-one in parser", ["Found while reviewing."])
        r = e.ship()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        calls = e.calls()
        for c in calls:
            if c.startswith(("pr view", "pr comment")):
                self.assertRegex(c, r"^pr (view|comment) 7\b", "must address the open PR by number: %r" % c)
        self.assertEqual(len([c for c in calls if c.startswith("pr list")]), 1, calls)
        st = e.state()
        self.assertEqual(st["closed_comments"], [])
        self.assertEqual(len(st["comments"]), 1)
        self.assertIn("fix off-by-one in parser", st["comments"][0])
        self.assertNotIn("add parser", st["comments"][0], "marker must come from the open PR, not the closed one")

    def test_create_after_unresolved_base_then_reship_lists_the_full_range(self):
        e = _Env(self, with_remote=False)
        _add_three_commits(e.repo)
        self.assertEqual(e.ship().returncode, 0)
        created = e.state()["created_bodies"]
        self.assertEqual(len(created), 1)
        self.assertIn("Commit list unavailable", created[0])
        self.assertEqual(MARKER_RE.findall(created[0]), [])

        bare = os.path.join(e.tmp, "origin.git")
        subprocess.run(["git", "init", "-q", "--bare", "-b", "main", bare], check=True, timeout=60)
        _git(["remote", "add", "origin", bare], e.repo)
        _git(["push", "-q", "origin", "main"], e.repo)
        r = e.ship()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        comments = e.state()["comments"]
        self.assertEqual(len(comments), 1, e.calls())
        for subject, _ in THREE_COMMITS:
            self.assertIn(subject, comments[0])

    def test_transient_lookup_failure_creates_nothing_comments_nothing_and_is_audited(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        e.set_state(exists=True, body="whatever", list_fail=True)
        r = e.ship()
        self.assertEqual(r.returncode, 0, "ship's push result stands: " + r.stdout + r.stderr)
        calls = e.calls()
        self.assertEqual([c for c in calls if c.startswith("pr create")], [])
        self.assertEqual([c for c in calls if c.startswith("pr comment")], [])
        self.assertEqual(e.state()["comments"], [])
        self.assertIn("could not determine whether a PR is already open", r.stderr)
        rows = e.audit_rows("ship-delta-publish")
        self.assertTrue(any(o == "block" and "open-change-request-failed" in d for o, d in rows), rows)

    def test_reused_pr_discards_the_body_and_comments_once_on_that_number(self):
        """The outcome is decided once, at open time: an open PR is reused
        (the rendered body is thrown away, never written), and the delta
        comment goes to exactly that number after exactly one lookup."""
        e = _Env(self)
        _add_three_commits(e.repo)
        e.set_state(exists=True, body="existing body, no marker")
        r = e.ship()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        calls = e.calls()
        self.assertEqual(len([c for c in calls if c.startswith("pr list")]), 1, calls)
        self.assertEqual([c for c in calls if c.startswith("pr create")], [])
        for c in calls:
            self.assertFalse(c.startswith("pr edit"), c)
            self.assertFalse(c.startswith("api"), c)
        comment_calls = [c for c in calls if c.startswith("pr comment")]
        self.assertEqual(len(comment_calls), 1, calls)
        self.assertTrue(comment_calls[0].startswith("pr comment 7 "), comment_calls[0])
        self.assertEqual(e.state()["body"], "existing body, no marker")

    def test_created_pr_makes_exactly_one_lookup_and_no_comment(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        r = e.ship()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        calls = e.calls()
        self.assertEqual(len([c for c in calls if c.startswith("pr list")]), 1, calls)
        self.assertEqual(len([c for c in calls if c.startswith("pr create")]), 1, calls)
        self.assertEqual([c for c in calls if c.startswith("pr comment")], [])

    def test_pr_opened_by_someone_else_after_the_lookup_is_never_edited_or_commented_on(self):
        """The window between lookup and create is the only race left: the
        create then fails, and nothing may be edited or commented as a
        consequence (no second, preflight-style view to go stale)."""
        e = _Env(self)
        _add_three_commits(e.repo)
        e.set_state(create_conflict=True)
        r = e.ship()
        self.assertEqual(r.returncode, 0, "ship's push result stands: " + r.stdout + r.stderr)
        calls = e.calls()
        self.assertEqual([c for c in calls if c.startswith(("pr comment", "pr edit"))], [])
        self.assertEqual(e.state()["comments"], [])
        rows = e.audit_rows("ship-delta-publish")
        self.assertTrue(any(o == "block" and "open-change-request-failed" in d for o, d in rows), rows)


    def test_two_open_prs_for_one_head_and_base_make_ship_create_and_comment_nothing(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        e.set_state(exists=True, extra_open=[{"number": "8", "head": "feat/example", "base": "main"}])
        r = e.ship()
        self.assertEqual(r.returncode, 0, "ship's push result stands: " + r.stdout + r.stderr)
        calls = e.calls()
        self.assertEqual([c for c in calls if c.startswith(("pr create", "pr comment"))], [])
        rows = e.audit_rows("ship-delta-publish")
        self.assertTrue(any(o == "block" and "open-change-request-failed" in d for o, d in rows), rows)


    def test_same_named_fork_pr_is_never_reused_by_ship(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        e.set_state(exists=False, extra_open=[
            {"number": "8", "head": "feat/example", "base": "main", "cross": True}])
        r = e.ship()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        calls = e.calls()
        self.assertEqual(len([c for c in calls if c.startswith("pr create")]), 1, calls)
        self.assertEqual([c for c in calls if c.startswith("pr comment 8")], [])

    def test_own_pr_is_still_found_next_to_a_same_named_fork_pr(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        e.set_state(exists=True, extra_open=[
            {"number": "8", "head": "feat/example", "base": "main", "cross": True}])
        r = e.ship()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        calls = e.calls()
        self.assertEqual([c for c in calls if c.startswith("pr create")], [], calls)
        self.assertEqual([c for c in calls if c.startswith("pr comment 8")], [])
        self.assertTrue(any(c.startswith("pr comment 7 ") for c in calls), calls)


class TestReviewVerdictPublisherLookup(unittest.TestCase):
    """The publisher finds its PR through the same lookup helper as ship, but
    head-only: it passes no base."""

    def _publish(self, e):
        head = _git(["rev-parse", "HEAD"], e.repo)
        env = os.environ.copy()
        env.update(source_env(gates=True))
        env.update({
            "CLAGENTIC_PROJECT_ROOT": e.repo, "CLAGENTIC_REPO_HOST": "github",
            "FAKE_GH_STATE": e.state_path,
            "FAKE_GH_GUARD_DIR": os.path.dirname(os.path.abspath(__file__)),
            "HOME": e.tmp, "PATH": e.bin + os.pathsep + env.get("PATH", ""),
        })
        script = ". '%s'\n_publish_review_verdict 'feat/example' pass '%s' '[]'\n" % (GATES_SH, head)
        return subprocess.run(["sh", "-c", script, GATES_SH], capture_output=True, text=True,
                              env=env, cwd=e.repo, timeout=60)

    def _env_with_audit_db(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        self.assertEqual(e.ship().returncode, 0)
        e.set_state(calls=[], comments=[])
        return e

    def test_comment_goes_to_the_open_pr_for_the_default_branch(self):
        e = self._env_with_audit_db()
        r = self._publish(e)
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertEqual(len(e.state()["comments"]), 1)
        lookups = [c for c in e.calls() if c.startswith("pr list")]
        self.assertEqual(len(lookups), 1, lookups)
        self.assertIn("--head feat/example --state open", lookups[0])
        self.assertNotIn("--base", lookups[0])

    def test_pr_with_a_non_default_base_gets_the_review_comment(self):
        e = self._env_with_audit_db()
        e.set_state(open_base="develop")
        r = self._publish(e)
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertEqual(len(e.state()["comments"]), 1)
        self.assertEqual(len([c for c in e.calls() if c.startswith("pr comment 7 ")]), 1, e.calls())

    def test_two_open_prs_for_one_head_post_nothing_and_audit_it(self):
        e = self._env_with_audit_db()
        e.set_state(exists=False, extra_open=[
            {"number": "8", "head": "feat/example", "base": "develop"},
            {"number": "9", "head": "feat/example", "base": "release"},
        ])
        r = self._publish(e)
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertEqual([c for c in e.calls() if c.startswith("pr comment")], [])
        rows = e.audit_rows("review-publish")
        self.assertTrue(any(o == "block" and "change-request-lookup-failed" in d for o, d in rows), rows)

    def test_same_named_fork_pr_never_receives_a_review_comment(self):
        e = self._env_with_audit_db()
        e.set_state(exists=False, extra_open=[
            {"number": "8", "head": "feat/example", "base": "main", "cross": True}])
        r = self._publish(e)
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertEqual([c for c in e.calls() if c.startswith("pr comment")], [])

    def test_own_pr_gets_the_review_comment_despite_a_fork_pr(self):
        e = self._env_with_audit_db()
        e.set_state(extra_open=[
            {"number": "8", "head": "feat/example", "base": "main", "cross": True}])
        r = self._publish(e)
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertEqual(len([c for c in e.calls() if c.startswith("pr comment 7 ")]), 1, e.calls())
        self.assertEqual([c for c in e.calls() if c.startswith("pr comment 8")], [])

    def test_no_open_pr_for_the_head_posts_nothing(self):
        e = self._env_with_audit_db()
        e.set_state(exists=False)
        r = self._publish(e)
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertEqual([c for c in e.calls() if c.startswith("pr comment")], [])
        rows = e.audit_rows("review-publish")
        self.assertTrue(any(o == "block" and "no-open-change-request" in d for o, d in rows), rows)

    def test_two_open_prs_for_the_default_base_are_an_error_and_post_nothing(self):
        e = self._env_with_audit_db()
        e.set_state(extra_open=[{"number": "8", "head": "feat/example", "base": "main"}])
        r = self._publish(e)
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertEqual([c for c in e.calls() if c.startswith("pr comment")], [])
        rows = e.audit_rows("review-publish")
        self.assertTrue(any(o == "block" and "change-request-lookup-failed" in d for o, d in rows), rows)


class TestAdapterContractAdditions(unittest.TestCase):
    def _run(self, e, call):
        env = os.environ.copy()
        env.update({"REPO_ROOT": e.repo, "FAKE_GH_STATE": e.state_path,
                    "FAKE_GH_GUARD_DIR": os.path.dirname(os.path.abspath(__file__)),
                    "CLAGENTIC_REPO_HOST": "github",
                    "PATH": e.bin + os.pathsep + env.get("PATH", "")})
        script = textwrap.dedent("""\
            . '%s'
            run_bounded() { _t="$1"; shift; [ "${1:-}" = "--" ] && shift; "$@"; }
            . '%s'
            %s
        """) % (PLATFORM_SH, HOST_ADAPTER_SH, call)
        return subprocess.run(["sh", "-c", script], capture_output=True, text=True, env=env, timeout=60)

    def test_open_outcome_is_created_or_reused_with_the_number(self):
        e = _Env(self)
        r = self._run(e, "host_adapter_open_change_request main feat/example")
        self.assertEqual((r.returncode, r.stdout.strip()), (0, "created 7"), r.stderr)
        r = self._run(e, "host_adapter_open_change_request main feat/example")
        self.assertEqual((r.returncode, r.stdout.strip()), (0, "reused 7"), r.stderr)

    def test_closed_pr_does_not_count_as_open(self):
        e = _Env(self)
        e.set_state(closed_pr=True)
        r = self._run(e, "host_adapter_open_change_request main feat/example")
        self.assertEqual(r.stdout.strip(), "created 7")

    def test_open_change_request_refuses_to_create_on_lookup_error(self):
        e = _Env(self)
        e.set_state(list_fail=True)
        r = self._run(e, "host_adapter_open_change_request main feat/example")
        self.assertNotEqual(r.returncode, 0)
        self.assertEqual(r.stdout.strip(), "")
        self.assertEqual([c for c in e.calls() if c.startswith("pr create")], [])

    def test_find_open_change_request_filters_on_head_and_base(self):
        e = _Env(self)
        e.set_state(exists=True, extra_open=[
            {"number": "8", "head": "other/head", "base": "main"},
            {"number": "9", "head": "feat/example", "base": "develop"},
        ])
        for head, base, want in (("feat/example", "main", (0, "7")),
                                 ("feat/example", "develop", (0, "9")),
                                 ("other/head", "main", (0, "8")),
                                 ("feat/example", "release", (1, "")),
                                 ("nobody/head", "main", (1, ""))):
            with self.subTest(head=head, base=base):
                r = self._run(e, "host_adapter_find_open_change_request %s %s" % (head, base))
                self.assertEqual((r.returncode, r.stdout.strip()), want, r.stderr)

    def test_find_open_change_request_base_is_optional_and_several_matches_are_an_error(self):
        e = _Env(self)
        e.set_state(exists=True, extra_open=[{"number": "8", "head": "feat/example", "base": "develop"},
                                             {"number": "9", "head": "other/head", "base": "main"}])
        r = self._run(e, "host_adapter_find_open_change_request feat/example main")
        self.assertEqual((r.returncode, r.stdout.strip()), (0, "7"))
        r = self._run(e, "host_adapter_find_open_change_request feat/example develop")
        self.assertEqual((r.returncode, r.stdout.strip()), (0, "8"))
        r = self._run(e, "host_adapter_find_open_change_request other/head")
        self.assertEqual((r.returncode, r.stdout.strip()), (0, "9"), "head-only lookup, no base")
        r = self._run(e, "host_adapter_find_open_change_request feat/example")
        self.assertEqual((r.returncode, r.stdout.strip()), (2, ""), "two open PRs for one head is an error")
        self.assertEqual(self._run(e, "host_adapter_find_open_change_request").returncode, 2)

    def test_read_thread_text_prints_body_then_comments(self):
        e = _Env(self)
        e.set_state(exists=True, body="the body", comments=["first comment", "second comment"])
        r = self._run(e, "host_adapter_read_thread_text 7")
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertEqual(r.stdout.split(), "the body first comment second comment".split())
        self.assertLess(r.stdout.index("the body"), r.stdout.index("first comment"))
        self.assertLess(r.stdout.index("first comment"), r.stdout.index("second comment"))

    def test_read_thread_text_failure_is_nonzero(self):
        e = _Env(self)
        e.set_state(exists=True, read_fail=True)
        self.assertNotEqual(self._run(e, "host_adapter_read_thread_text 7").returncode, 0)

    def test_read_thread_text_by_number_never_reads_the_closed_pr(self):
        e = _Env(self)
        e.set_state(exists=True, body="open body", comments=["open comment"], closed_pr=True,
                    closed_body="closed body", closed_comments=["closed comment"])
        r = self._run(e, "host_adapter_read_thread_text 7")
        self.assertIn("open body", r.stdout)
        self.assertNotIn("closed", r.stdout)

    def test_no_adapter_code_path_can_edit_a_pr_body(self):
        """Sweep over the tracked gate/adapter scripts: no body-edit verb
        exists anywhere, so the create-only invariant cannot be broken by a
        code path nobody wrote a test for."""
        tracked, violations = _sweep_for_pr_body_edits(SCRIPTS_DIR)
        self.assertTrue(tracked)
        self.assertEqual(violations, [])

    def test_sweep_catches_every_body_edit_shape(self):
        shapes = [
            'gh pr edit 1 --body x',
            '"$GH" pr edit "$N" --body-file f',
            'gh api repos/o/r/pulls/1 -X PATCH -f body=x',
            '"$GH" api repos/o/r/pulls/1 -X PATCH -f body=x',
            '$HOST_CLI api repos/o/r/pulls/1 --method PATCH',
            '/usr/bin/ghx api -XPATCH repos/o/r/pulls/1',
            '"$GH" api repos/o/r/pulls/1 \\\n  --method PATCH \\\n  -f body=x',
        ]
        for shape in shapes:
            with self.subTest(shape=shape):
                found = [n for n, text in _logical_lines(shape.split("\n")) if _line_edits_pr_body(text)]
                self.assertTrue(found, "body-edit shape not caught: %r" % shape)

    def test_sweep_does_not_flag_read_only_calls(self):
        for ok in ['gh pr list --head b --state open', 'gh pr comment 7 --body-file f',
                   'echo "the api is stable"', '# gh api -X PATCH in a comment']:
            with self.subTest(line=ok):
                found = [n for n, text in _logical_lines(ok.split("\n")) if _line_edits_pr_body(text)]
                self.assertEqual(found, [])

    def test_sweep_sees_scripts_in_subdirectories(self):
        tmp = tempfile.mkdtemp(prefix="clagentic-test-sweep-")
        self.addCleanup(shutil.rmtree, tmp, ignore_errors=True)
        subprocess.run(["git", "init", "-q", tmp], check=True, timeout=60)
        os.makedirs(os.path.join(tmp, "sub"))
        with open(os.path.join(tmp, "top.sh"), "w") as f:
            f.write("echo ok\n")
        with open(os.path.join(tmp, "sub", "nested.sh"), "w") as f:
            f.write("gh pr edit 1 --body x\n")
        _git(["add", "top.sh", "sub/nested.sh"], tmp)
        tracked, violations = _sweep_for_pr_body_edits(tmp)
        self.assertIn(os.path.join("sub", "nested.sh"), tracked)
        self.assertEqual([v[0] for v in violations], [os.path.join("sub", "nested.sh")])


if __name__ == "__main__":
    unittest.main()
