"""
Regression guards for the ship-time PR body losing its commit text.

BACKGROUND: `gates ship` once opened PRs with the host CLI's own
commit-message fill, so the PR body carried every commit subject and body.
A later change switched to a rendered body file, and the rendered "What
changed and why" section became a placeholder -- the commit text was
discarded. Nothing compared the produced body to the prior one: the renderer
and the adapter were tested in isolation, and the old test asserted the
placeholder itself.

SCOPE:
  1. _build_ship_pr_body's section 1 is the branch's own commits (subject +
     full body, oldest first), generated by clagentic-lite from git so tests
     assert on content, not on a vendor flag's semantics.
  2. End to end through cmd_ship with a stub host CLI that captures the body
     file: the captured body contains the commit text (the
     renderer-to-adapter seam that let this regress).
  3. Re-ship to an existing PR: the body is never edited; exactly one delta
     comment lists the commits added since the last ship, anchored by a
     hidden marker read back from the PR thread.
  4. Placeholder only when the range is genuinely empty or unresolvable.
  5. Truncation is bounded and explicit.

Every host interaction runs against a stateful stub `gh` on PATH -- no
network, no real host. This proves clagentic-lite's own output, not the
behavior of a real host (operator-side validation, see docs/GATES.md).

Run with: python3 -m unittest scripts.test_ship_commits_body -v
"""
import json
import os
import re
import shutil
import sqlite3
import stat
import subprocess
import sys
import tempfile
import textwrap
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from test_source_helpers import GATES_SH, HOST_ADAPTER_SH, PLATFORM_SH, SCRIPTS_DIR, source_env  # noqa: E402

_GIT_ENV = {
    "GIT_AUTHOR_NAME": "test", "GIT_AUTHOR_EMAIL": "test@example.com",
    "GIT_COMMITTER_NAME": "test", "GIT_COMMITTER_EMAIL": "test@example.com",
}

MARKER_RE = re.compile(r"<!-- clagentic-lite:shipped-head=([0-9a-f]{40,64}) -->")
BODY_HEADING = "## What changed and why"
NEXT_HEADING = "## Review provenance"


def _git(args, cwd):
    env = {**os.environ, **_GIT_ENV}
    return subprocess.run(["git"] + args, cwd=cwd, env=env, check=True,
                          capture_output=True, text=True, timeout=60).stdout.strip()


def _commit(repo, name, subject, body_lines=None):
    path = os.path.join(repo, name)
    with open(path, "a") as f:
        f.write("%s\n" % subject)
    _git(["add", name], repo)
    args = ["commit", "-q", "-m", subject]
    if body_lines:
        args += ["-m", "\n".join(body_lines)]
    _git(args, repo)
    return _git(["rev-parse", "HEAD"], repo)


def _make_repo(tmp, with_remote=True):
    """A repo on feat/example, one seed commit on main. With a remote: a
    local bare origin that already has main, so origin/main resolves."""
    repo = os.path.join(tmp, "repo")
    subprocess.run(["git", "init", "-q", "-b", "main", repo], check=True, timeout=60)
    _commit(repo, "seed.txt", "seed")
    if with_remote:
        bare = os.path.join(tmp, "origin.git")
        subprocess.run(["git", "init", "-q", "--bare", "-b", "main", bare], check=True, timeout=60)
        _git(["remote", "add", "origin", bare], repo)
        _git(["push", "-q", "origin", "main"], repo)
    _git(["checkout", "-q", "-b", "feat/example"], repo)
    return repo


THREE_COMMITS = [
    ("add parser", ["Parses the widget format.", "Handles empty input explicitly."]),
    ("wire parser into cli", ["Adds the --widget flag.", "", "Second paragraph of the body."]),
    ("document widget flag", ["## not a real heading, just body text", "Co-Authored-By: Someone <s@example.com>"]),
]


def _add_three_commits(repo):
    for i, (subject, body) in enumerate(THREE_COMMITS):
        _commit(repo, "f%d.txt" % i, subject, body)


def _call_build_ship_pr_body(repo, head, env_extra=None):
    env = os.environ.copy()
    env.update(source_env(gates=True))
    env["CLAGENTIC_PROJECT_ROOT"] = repo
    if env_extra:
        env.update(env_extra)
    script = ". '%s'\n_build_ship_pr_body 'feat/example' '%s'\n" % (GATES_SH, head)
    return subprocess.run(["sh", "-c", script, GATES_SH], capture_output=True, text=True,
                          env=env, cwd=repo, timeout=60)


def _section_one(body):
    start = body.index(BODY_HEADING) + len(BODY_HEADING)
    return body[start:body.index(NEXT_HEADING)]


def _sweep_for_pr_body_edits(root):
    """Return (tracked shell paths, [(path, line_no)] body-edit hits). Paths
    are repo-relative exactly as ls-files prints them and are opened under
    root as-is, so a script in a subdirectory is read, not skipped."""
    tracked = subprocess.run(["git", "-C", root, "ls-files", "*.sh"],
                             capture_output=True, text=True, check=True, timeout=30).stdout.split()
    hits = []
    for rel in tracked:
        with open(os.path.join(root, rel), encoding="utf-8") as f:
            lines = f.read().splitlines()
        for n, logical in _logical_lines(lines):
            if _line_edits_pr_body(logical):
                hits.append((rel, n))
    return tracked, hits


def _logical_lines(lines):
    """Yield (first_line_no, text) with backslash continuations joined and
    comment lines dropped, so `... api path \\` + `-X PATCH` is one line."""
    out, buf, start = [], "", 0
    for n, raw in enumerate(lines, 1):
        if not buf and raw.strip().startswith("#"):
            continue
        if not buf:
            start = n
        if raw.rstrip().endswith("\\"):
            buf += raw.rstrip()[:-1] + " "
            continue
        out.append((start, buf + raw))
        buf = ""
    if buf:
        out.append((start, buf))
    return out


_API_WORD = re.compile(r"\bapi\b")
_WRITE_VERB = re.compile(r"(?i:\bPATCH\b|\bPUT\b)|(?:^|\s)-X\s*\w*|--method\b")


def _line_edits_pr_body(line):
    """True for any shape that could rewrite a PR body: `pr edit` through any
    binary, a literal `gh api`, or an `api` subcommand through a variable- or
    path-named binary combined with PATCH/PUT, -X or --method."""
    if re.search(r"\bpr\s+edit\b", line) or re.search(r"\bgh\s+api\b", line):
        return True
    return bool(_API_WORD.search(line) and _WRITE_VERB.search(line))


_FAKE_GH = textwrap.dedent('''\
    #!/usr/bin/env python3
    import json, os, sys

    state_path = os.environ["FAKE_GH_STATE"]
    argv = sys.argv[1:]
    with open(state_path) as f:
        st = json.load(f)
    st["calls"].append(argv)

    def save():
        with open(state_path, "w") as f:
            json.dump(st, f)

    def body_file():
        with open(argv[argv.index("--body-file") + 1]) as f:
            return f.read()

    OPEN_NUMBER, CLOSED_NUMBER = "7", "3"

    def target_is_closed():
        # A numeric ref addresses exactly one PR. A bare branch name is
        # ambiguous when a closed and an open PR share it; the stub resolves
        # it to the CLOSED one, the wrong-PR hazard being guarded against.
        ref = argv[2]
        if ref == CLOSED_NUMBER:
            return True
        if ref == OPEN_NUMBER:
            return False
        return bool(st.get("closed_pr"))

    rc = 0
    if argv[:2] == ["pr", "view"] and "--json" in argv:
        if st.get("read_fail"):
            sys.stderr.write("simulated read failure\\n")
            rc = 1
        elif target_is_closed():
            print(st.get("closed_body", ""))
            for c in st.get("closed_comments", []):
                print(c)
        else:
            print(st["body"])
            for c in st["comments"]:
                print(c)
    elif argv[:2] == ["pr", "list"]:
        # Open-PR lookup honoring --state (default open), modelling one open
        # PR (number 7, when "exists") and one closed PR (number 3, when
        # "closed_pr") on the same branch.
        if st.get("list_fail"):
            sys.stderr.write("simulated transient host failure\\n")
            rc = 1
        else:
            wanted = argv[argv.index("--state") + 1] if "--state" in argv else "open"
            numbers = []
            if st["exists"] and wanted in ("open", "all"):
                numbers.append(OPEN_NUMBER)
            if st.get("closed_pr") and wanted in ("closed", "all"):
                numbers.append(CLOSED_NUMBER)
            if numbers:
                print(numbers[0])
    elif argv[:2] == ["pr", "view"]:
        # Bare view matches closed/merged PRs too, as the real CLI does.
        rc = 0 if (st["exists"] or st.get("closed_pr")) else 1
    elif argv[:2] == ["pr", "create"]:
        st["exists"] = True
        st["body"] = body_file() if "--body-file" in argv else ""
        st["created_bodies"].append(st["body"])
    elif argv[:2] == ["pr", "comment"]:
        key = "closed_comments" if target_is_closed() else "comments"
        st.setdefault(key, []).append(body_file())
    save()
    sys.exit(rc)
''')


class _Env:
    """Temp dir + repo + stub gh + audit db, torn down by the test."""

    def __init__(self, test, with_remote=True):
        self.tmp = tempfile.mkdtemp(prefix="clagentic-test-ship-commits-")
        test.addCleanup(shutil.rmtree, self.tmp, ignore_errors=True)
        self.repo = _make_repo(self.tmp, with_remote=with_remote)
        self.bin = os.path.join(self.tmp, "bin")
        os.makedirs(self.bin)
        gh = os.path.join(self.bin, "gh")
        with open(gh, "w") as f:
            f.write(_FAKE_GH)
        os.chmod(gh, stat.S_IRWXU)
        self.state_path = os.path.join(self.tmp, "gh-state.json")
        self.set_state(exists=False, body="", comments=[], calls=[], created_bodies=[],
                       read_fail=False, list_fail=False, closed_pr=False)

    def set_state(self, **kw):
        st = self.state() if os.path.exists(self.state_path) else {}
        st.update(kw)
        with open(self.state_path, "w") as f:
            json.dump(st, f)

    def state(self):
        with open(self.state_path) as f:
            return json.load(f)

    def ship(self):
        env = os.environ.copy()
        env.update({
            "CLAGENTIC_PROJECT_ROOT": self.repo,
            "CLAGENTIC_GATES": "none",
            "CLAGENTIC_REPO_HOST": "github",
            "FAKE_GH_STATE": self.state_path,
            "HOME": self.tmp,
            "PATH": self.bin + os.pathsep + env.get("PATH", ""),
        })
        r = subprocess.run(["sh", GATES_SH, "ship"], cwd=self.repo, env=env,
                           capture_output=True, text=True, timeout=180)
        return r

    def calls(self):
        return [" ".join(c) for c in self.state()["calls"]]

    def audit_rows(self, gate):
        db = os.path.join(self.repo, ".clagentic", "lite", "audit.db")
        conn = sqlite3.connect(db)
        try:
            return conn.execute("SELECT outcome, details FROM gate_runs WHERE gate=?", (gate,)).fetchall()
        finally:
            conn.close()


class TestBuildShipPrBodyCarriesCommits(unittest.TestCase):
    def test_every_subject_and_body_line_appears_oldest_first(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        head = _git(["rev-parse", "HEAD"], e.repo)
        r = _call_build_ship_pr_body(e.repo, head)
        self.assertEqual(r.returncode, 0, r.stderr)
        section = _section_one(r.stdout)
        last = -1
        for subject, body in THREE_COMMITS:
            pos = section.index(subject)
            self.assertGreater(pos, last, "commits must be listed oldest first")
            last = pos
            for line in body:
                if line:
                    self.assertIn(line, section)

    def test_false_summarizer_claim_is_gone(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        r = _call_build_ship_pr_body(e.repo, _git(["rev-parse", "HEAD"], e.repo))
        self.assertNotIn("summarizer", r.stdout)

    def test_body_ends_with_marker_for_shipped_head(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        head = _git(["rev-parse", "HEAD"], e.repo)
        r = _call_build_ship_pr_body(e.repo, head)
        self.assertEqual(MARKER_RE.findall(r.stdout), [head])

    def test_merge_commits_are_not_listed(self):
        e = _Env(self)
        _commit(e.repo, "a.txt", "feature work")
        _git(["checkout", "-q", "-b", "side", "main"], e.repo)
        _commit(e.repo, "b.txt", "side work")
        _git(["checkout", "-q", "feat/example"], e.repo)
        _git(["merge", "-q", "--no-ff", "-m", "Merge branch side", "side"], e.repo)
        r = _call_build_ship_pr_body(e.repo, _git(["rev-parse", "HEAD"], e.repo))
        section = _section_one(r.stdout)
        self.assertIn("feature work", section)
        self.assertIn("side work", section)
        self.assertNotIn("Merge branch side", section)


class TestPlaceholderOnlyWhenRangeUnavailable(unittest.TestCase):
    PLACEHOLDER_MARKERS = ("Commit list unavailable", "No commits to list")

    def test_no_placeholder_when_commits_exist(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        r = _call_build_ship_pr_body(e.repo, _git(["rev-parse", "HEAD"], e.repo))
        for m in self.PLACEHOLDER_MARKERS:
            self.assertNotIn(m, r.stdout)

    def test_unresolvable_range_states_the_actual_reason(self):
        e = _Env(self, with_remote=False)
        _add_three_commits(e.repo)
        r = _call_build_ship_pr_body(e.repo, _git(["rev-parse", "HEAD"], e.repo))
        section = _section_one(r.stdout)
        self.assertIn("Commit list unavailable", section)
        self.assertIn("cannot establish a provably current baseline", section)

    def test_empty_range_says_so(self):
        e = _Env(self)
        r = _call_build_ship_pr_body(e.repo, _git(["rev-parse", "HEAD"], e.repo))
        section = _section_one(r.stdout)
        self.assertIn("No commits to list", section)
        self.assertNotIn("Commit list unavailable", section)

    def test_unresolved_head_states_the_actual_reason(self):
        e = _Env(self)
        r = _call_build_ship_pr_body(e.repo, "")
        self.assertIn("the shipped head commit could not be resolved", _section_one(r.stdout))
        self.assertEqual(MARKER_RE.findall(r.stdout), [])

    def test_no_marker_when_base_is_unresolved(self):
        e = _Env(self, with_remote=False)
        _add_three_commits(e.repo)
        r = _call_build_ship_pr_body(e.repo, _git(["rev-parse", "HEAD"], e.repo))
        self.assertIn("Commit list unavailable", r.stdout)
        self.assertEqual(MARKER_RE.findall(r.stdout), [],
                         "a marker for a head whose commits were never listed hides them from later ships")

    def test_no_marker_when_range_is_empty(self):
        e = _Env(self)
        r = _call_build_ship_pr_body(e.repo, _git(["rev-parse", "HEAD"], e.repo))
        self.assertIn("No commits to list", r.stdout)
        self.assertEqual(MARKER_RE.findall(r.stdout), [])


class TestCommitBodyCannotBecomeMarkdownStructure(unittest.TestCase):
    HOSTILE = ["## X", "```", "injected after a fence", "````", "# Another", "---"]

    def test_hostile_body_is_confined_to_a_fence_longer_than_any_backtick_run(self):
        e = _Env(self)
        _commit(e.repo, "h.txt", "hostile body", self.HOSTILE)
        _commit(e.repo, "i.txt", "innocent follow-up", ["plain text"])
        r = _call_build_ship_pr_body(e.repo, _git(["rev-parse", "HEAD"], e.repo))
        self.assertEqual(r.returncode, 0, r.stderr)
        section = _section_one(r.stdout)
        lines = section.split("\n")
        fence_re = re.compile(r"^ {2}(`{3,})$")
        fences = [(i, fence_re.match(l).group(1)) for i, l in enumerate(lines) if fence_re.match(l)]
        open_i, open_f = fences[0]
        self.assertGreater(len(open_f), 4, "fence must outrun the longest backtick run (4) in the body")
        # The first line that can close the fence is the first one at least as
        # long as the opener; the body's own 3- and 4-backtick lines cannot.
        close_i = next(i for i, f in fences[1:] if len(f) >= len(open_f))
        self.assertEqual(lines[close_i].strip(), open_f)
        inside = lines[open_i + 1:close_i]
        self.assertIn("  ```", inside)
        self.assertIn("  # Another", inside)
        self.assertIn("  ## X", inside)
        self.assertIn("  injected after a fence", inside)
        self.assertEqual([l for l in lines[:open_i] if l.startswith("#")], [])
        self.assertIn("innocent follow-up", section)
        self.assertIn(NEXT_HEADING, r.stdout)


class TestBaseResolverStderrIsNotPartOfTheRef(unittest.TestCase):
    def test_resolver_warning_on_stderr_still_yields_a_correct_commit_list(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        head = _git(["rev-parse", "HEAD"], e.repo)
        main_tip = _git(["rev-parse", "main"], e.repo)
        env = os.environ.copy()
        env.update(source_env(gates=True))
        env["CLAGENTIC_PROJECT_ROOT"] = e.repo
        script = textwrap.dedent("""\
            . '%s'
            _gate_resolve_fresh_default_branch_ref() {
              echo "WARN: something noisy on stderr" 1>&2
              printf '%%s\\n' '%s'
            }
            _build_ship_pr_body 'feat/example' '%s'
        """) % (GATES_SH, main_tip, head)
        r = subprocess.run(["sh", "-c", script, GATES_SH], capture_output=True, text=True,
                           env=env, cwd=e.repo, timeout=60)
        self.assertEqual(r.returncode, 0, r.stderr)
        section = _section_one(r.stdout)
        self.assertNotIn("Commit list unavailable", section)
        self.assertNotIn("WARN", r.stdout)
        for subject, _ in THREE_COMMITS:
            self.assertIn(subject, section)


class TestTruncation(unittest.TestCase):
    def test_oversize_range_is_bounded_with_explicit_count(self):
        e = _Env(self)
        for i in range(10):
            _commit(e.repo, "f%d.txt" % i, "commit number %d" % i, ["x" * 300])
        head = _git(["rev-parse", "HEAD"], e.repo)
        r = _call_build_ship_pr_body(e.repo, head, {"CLAGENTIC_SHIP_COMMITS_MAX_CHARS": "1500"})
        self.assertEqual(r.returncode, 0, r.stderr)
        section = _section_one(r.stdout)
        shown = len(re.findall(r"^- commit number \d+ \(", section, re.M))
        m = re.search(r"_(\d+) more commits not shown", section)
        self.assertIsNotNone(m, "truncation must be explicit, never silent")
        self.assertGreater(shown, 0)
        self.assertEqual(shown + int(m.group(1)), 10)
        self.assertLessEqual(len(section), 1500 + 300)
        self.assertIn("commit number 0 (", section, "oldest commits are the ones kept")

    def test_single_oversize_commit_body_is_cut_by_lines_with_count(self):
        e = _Env(self)
        _commit(e.repo, "big.txt", "huge commit", ["line %d %s" % (i, "y" * 40) for i in range(200)])
        head = _git(["rev-parse", "HEAD"], e.repo)
        r = _call_build_ship_pr_body(e.repo, head, {"CLAGENTIC_SHIP_COMMITS_MAX_CHARS": "1000"})
        section = _section_one(r.stdout)
        self.assertIn("huge commit", section)
        self.assertRegex(section, r"\[commit body truncated: \d+ more lines not shown\]")
        self.assertLessEqual(len(section), 1000 + 300)


class TestShipEndToEnd(unittest.TestCase):
    def test_created_body_captured_by_stub_contains_commit_text(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        r = e.ship()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        created = e.state()["created_bodies"]
        self.assertEqual(len(created), 1)
        for subject, body in THREE_COMMITS:
            self.assertIn(subject, created[0])
            for line in body:
                if line:
                    self.assertIn(line, created[0])
        self.assertEqual(MARKER_RE.findall(created[0]), [_git(["rev-parse", "HEAD"], e.repo)])
        self.assertEqual(e.state()["comments"], [], "a fresh PR gets a body, not a comment")

    def test_reship_with_new_commit_posts_one_comment_and_never_edits_body(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        self.assertEqual(e.ship().returncode, 0)
        original_body = e.state()["body"]
        e.set_state(calls=[])

        _commit(e.repo, "f9.txt", "fix off-by-one in parser", ["Found while reviewing."])
        new_head = _git(["rev-parse", "HEAD"], e.repo)
        r = e.ship()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)

        calls = e.calls()
        self.assertEqual([c for c in calls if c.startswith("pr create")], [])
        self.assertEqual(len([c for c in calls if c.startswith("pr comment")]), 1, calls)
        for c in calls:
            self.assertFalse(c.startswith("pr edit"), "no code path may edit a PR body: %r" % c)
            self.assertFalse(c.startswith("api"), c)
            if not c.startswith("pr comment"):
                self.assertNotIn("--body", c)
        st = e.state()
        self.assertEqual(st["body"], original_body, "body must be untouched on re-ship")
        comment = st["comments"][0]
        self.assertIn("fix off-by-one in parser", comment)
        self.assertIn("Found while reviewing.", comment)
        for subject, _ in THREE_COMMITS:
            self.assertNotIn(subject, comment, "only post-marker commits belong in the delta")
        self.assertEqual(MARKER_RE.findall(comment), [new_head])

    def test_reship_with_no_new_commits_posts_nothing(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        self.assertEqual(e.ship().returncode, 0)
        e.set_state(calls=[])
        r = e.ship()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        self.assertEqual([c for c in e.calls() if c.startswith("pr comment")], [])
        self.assertEqual(e.state()["comments"], [])

    def test_third_ship_anchors_on_the_newest_marker_in_a_comment(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        self.assertEqual(e.ship().returncode, 0)
        _commit(e.repo, "g1.txt", "second wave one")
        self.assertEqual(e.ship().returncode, 0)
        _commit(e.repo, "g2.txt", "third wave two")
        self.assertEqual(e.ship().returncode, 0)
        comments = e.state()["comments"]
        self.assertEqual(len(comments), 2)
        self.assertIn("third wave two", comments[1])
        self.assertNotIn("second wave one", comments[1])

    def test_rewritten_history_posts_full_list_with_reason(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        self.assertEqual(e.ship().returncode, 0)
        _git(["commit", "-q", "--amend", "-m", "document widget flag (reworded)"], e.repo)
        _git(["push", "-q", "-f", "origin", "feat/example"], e.repo)
        e.set_state(calls=[])
        r = e.ship()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        comments = e.state()["comments"]
        self.assertEqual(len(comments), 1)
        self.assertIn("History was rewritten", comments[0])
        for subject, _ in THREE_COMMITS[:2]:
            self.assertIn(subject, comments[0])
        self.assertIn("document widget flag (reworded)", comments[0])

    def test_pr_without_a_marker_gets_full_list_with_reason(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        e.set_state(exists=True, body="hand-written description, no marker")
        r = e.ship()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        comments = e.state()["comments"]
        self.assertEqual(len(comments), 1)
        self.assertIn("No earlier ship marker", comments[0])
        for subject, _ in THREE_COMMITS:
            self.assertIn(subject, comments[0])
        self.assertEqual(e.state()["body"], "hand-written description, no marker")

    def test_thread_read_failure_posts_nothing_and_is_audit_logged(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        e.set_state(exists=True, body="whatever", read_fail=True)
        r = e.ship()
        self.assertEqual(r.returncode, 0, "a publish problem must never block ship: " + r.stdout + r.stderr)
        self.assertEqual(e.state()["comments"], [])
        self.assertEqual([c for c in e.calls() if c.startswith("pr comment")], [])
        rows = e.audit_rows("ship-delta-publish")
        self.assertTrue(any(o == "block" and "thread-read-failed" in d for o, d in rows), rows)


class TestShipPrLookupStates(unittest.TestCase):
    def test_closed_pr_for_a_reused_branch_creates_a_new_pr_and_posts_no_comment(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        e.set_state(closed_pr=True)
        r = e.ship()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        st = e.state()
        self.assertEqual(len(st["created_bodies"]), 1, e.calls())
        for subject, _ in THREE_COMMITS:
            self.assertIn(subject, st["created_bodies"][0])
        self.assertEqual(st["comments"], [])

    def test_closed_and_open_pr_on_one_branch_read_and_comment_target_the_open_number(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        self.assertEqual(e.ship().returncode, 0)
        # A stale CLOSED PR on the same branch, carrying a decoy marker that
        # would mislead a wrong-PR read into listing the full range.
        e.set_state(closed_pr=True, closed_body="old PR, no marker", closed_comments=[], calls=[])
        _commit(e.repo, "f9.txt", "fix off-by-one in parser", ["Found while reviewing."])
        r = e.ship()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        calls = e.calls()
        for c in calls:
            if c.startswith(("pr view", "pr comment")):
                self.assertRegex(c, r"^pr (view|comment) 7\b", "must address the open PR by number: %r" % c)
        st = e.state()
        self.assertEqual(st["closed_comments"], [])
        self.assertEqual(len(st["comments"]), 1)
        self.assertIn("fix off-by-one in parser", st["comments"][0])
        self.assertNotIn("add parser", st["comments"][0], "marker must come from the open PR, not the closed one")

    def test_create_after_unresolved_base_then_reship_lists_the_full_range(self):
        e = _Env(self, with_remote=False)
        _add_three_commits(e.repo)
        self.assertEqual(e.ship().returncode, 0)
        created = e.state()["created_bodies"]
        self.assertEqual(len(created), 1)
        self.assertIn("Commit list unavailable", created[0])
        self.assertEqual(MARKER_RE.findall(created[0]), [])

        bare = os.path.join(e.tmp, "origin.git")
        subprocess.run(["git", "init", "-q", "--bare", "-b", "main", bare], check=True, timeout=60)
        _git(["remote", "add", "origin", bare], e.repo)
        _git(["push", "-q", "origin", "main"], e.repo)
        r = e.ship()
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        comments = e.state()["comments"]
        self.assertEqual(len(comments), 1, e.calls())
        for subject, _ in THREE_COMMITS:
            self.assertIn(subject, comments[0])

    def test_transient_lookup_failure_creates_nothing_comments_nothing_and_is_audited(self):
        e = _Env(self)
        _add_three_commits(e.repo)
        e.set_state(exists=True, body="whatever", list_fail=True)
        r = e.ship()
        self.assertEqual(r.returncode, 0, "ship's push result stands: " + r.stdout + r.stderr)
        calls = e.calls()
        self.assertEqual([c for c in calls if c.startswith("pr create")], [])
        self.assertEqual([c for c in calls if c.startswith("pr comment")], [])
        self.assertEqual(e.state()["comments"], [])
        self.assertIn("could not determine whether a PR is already open", r.stderr)
        rows = e.audit_rows("ship-delta-publish")
        self.assertTrue(any(o == "block" and "pr-existence-check-failed" in d for o, d in rows), rows)


class TestAdapterContractAdditions(unittest.TestCase):
    def _run(self, e, call):
        env = os.environ.copy()
        env.update({"REPO_ROOT": e.repo, "FAKE_GH_STATE": e.state_path,
                    "CLAGENTIC_REPO_HOST": "github",
                    "PATH": e.bin + os.pathsep + env.get("PATH", "")})
        script = textwrap.dedent("""\
            . '%s'
            run_bounded() { _t="$1"; shift; [ "${1:-}" = "--" ] && shift; "$@"; }
            . '%s'
            %s
        """) % (PLATFORM_SH, HOST_ADAPTER_SH, call)
        return subprocess.run(["sh", "-c", script], capture_output=True, text=True, env=env, timeout=60)

    def test_exists_is_tri_state(self):
        e = _Env(self)
        call = "host_adapter_change_request_exists feat/example"
        self.assertEqual(self._run(e, call).returncode, 1)
        e.set_state(exists=True)
        self.assertEqual(self._run(e, call).returncode, 0)
        e.set_state(exists=True, list_fail=True)
        self.assertEqual(self._run(e, call).returncode, 2)

    def test_closed_pr_does_not_count_as_open(self):
        e = _Env(self)
        e.set_state(closed_pr=True)
        self.assertEqual(self._run(e, "host_adapter_change_request_exists feat/example").returncode, 1)

    def test_open_change_request_refuses_to_create_on_lookup_error(self):
        e = _Env(self)
        e.set_state(list_fail=True)
        r = self._run(e, "host_adapter_open_change_request main feat/example")
        self.assertNotEqual(r.returncode, 0)
        self.assertEqual([c for c in e.calls() if c.startswith("pr create")], [])

    def test_read_thread_text_prints_body_then_comments(self):
        e = _Env(self)
        e.set_state(exists=True, body="the body", comments=["first comment", "second comment"])
        r = self._run(e, "host_adapter_read_thread_text feat/example")
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertEqual(r.stdout.split(), "the body first comment second comment".split())
        self.assertLess(r.stdout.index("the body"), r.stdout.index("first comment"))
        self.assertLess(r.stdout.index("first comment"), r.stdout.index("second comment"))

    def test_read_thread_text_failure_is_nonzero(self):
        e = _Env(self)
        e.set_state(exists=True, read_fail=True)
        self.assertNotEqual(self._run(e, "host_adapter_read_thread_text feat/example").returncode, 0)

    def test_no_adapter_code_path_can_edit_a_pr_body(self):
        """Sweep over the tracked gate/adapter scripts: no body-edit verb
        exists anywhere, so the create-only invariant cannot be broken by a
        code path nobody wrote a test for."""
        tracked, violations = _sweep_for_pr_body_edits(SCRIPTS_DIR)
        self.assertTrue(tracked)
        self.assertEqual(violations, [])

    def test_sweep_catches_every_body_edit_shape(self):
        shapes = [
            'gh pr edit 1 --body x',
            '"$GH" pr edit "$N" --body-file f',
            'gh api repos/o/r/pulls/1 -X PATCH -f body=x',
            '"$GH" api repos/o/r/pulls/1 -X PATCH -f body=x',
            '$HOST_CLI api repos/o/r/pulls/1 --method PATCH',
            '/usr/bin/ghx api -XPATCH repos/o/r/pulls/1',
            '"$GH" api repos/o/r/pulls/1 \\\n  --method PATCH \\\n  -f body=x',
        ]
        for shape in shapes:
            with self.subTest(shape=shape):
                found = [n for n, text in _logical_lines(shape.split("\n")) if _line_edits_pr_body(text)]
                self.assertTrue(found, "body-edit shape not caught: %r" % shape)

    def test_sweep_does_not_flag_read_only_calls(self):
        for ok in ['gh pr list --head b --state open', 'gh pr comment 7 --body-file f',
                   'echo "the api is stable"', '# gh api -X PATCH in a comment']:
            with self.subTest(line=ok):
                found = [n for n, text in _logical_lines(ok.split("\n")) if _line_edits_pr_body(text)]
                self.assertEqual(found, [])

    def test_sweep_sees_scripts_in_subdirectories(self):
        tmp = tempfile.mkdtemp(prefix="clagentic-test-sweep-")
        self.addCleanup(shutil.rmtree, tmp, ignore_errors=True)
        subprocess.run(["git", "init", "-q", tmp], check=True, timeout=60)
        os.makedirs(os.path.join(tmp, "sub"))
        with open(os.path.join(tmp, "top.sh"), "w") as f:
            f.write("echo ok\n")
        with open(os.path.join(tmp, "sub", "nested.sh"), "w") as f:
            f.write("gh pr edit 1 --body x\n")
        _git(["add", "top.sh", "sub/nested.sh"], tmp)
        tracked, violations = _sweep_for_pr_body_edits(tmp)
        self.assertIn(os.path.join("sub", "nested.sh"), tracked)
        self.assertEqual([v[0] for v in violations], [os.path.join("sub", "nested.sh")])


if __name__ == "__main__":
    unittest.main()
